name: Daily Automation

on:
  schedule:
    - cron: "0 11,23 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_API: ${{ secrets.GOOGLE_API }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py

      # 👇 ADD THIS STEP HERE
      - name: Commit updated user.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add user.json
          git commit -m "update user index" || exit 0
          git push
